[default_session]
startup_command = "nvim -c ':Telescope find_files'"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "tmux config"
path = "~"
startup_command = "nvim .tmux.conf"
preview_command = "bat --color=always ~/c/dotfiles/.config/tmux/tmux.conf"

[[session]]
name = "zshrc config"
path = "~"
startup_command = "nvim ~/.zshrc"
preview_command = "bat --color=always ~/.zshrc"

[[session]]
name = "nvim config"
path = "~/.config/nvim"
startup_command = "nvim"

[[session]]
name = "config"
path = "~/.config"
startup_command = "nvim"

[[session]]
name = "hemea-main"
path = "~/Developer/travauxlib"
startup_command = "tmux kill-session -t hemea-all && main"

[[session]]
name = "hemea-all"
path = "~/Developer/travauxlib"
startup_command = "tmux kill-session -t hemea-main && tmux kill-session -t hemea-shared && all"

[[session]]
name = "hemea-shared"
path = "~/Developer/travauxlib"
startup_command = "tmux kill-session -t hemea-all && shared"
